================================================================================
Added a new command-line option to tmda-inject and tmda-filter.  `-M'
or `--filter-match' can be used to test whether a given e-mail address
matches your incoming and outgoing filter files.  The results are
printed to stdout.  These options will also report any parsing
errors encountered in the filter files first.

tmda-inject -M expects a hypothetical recipient address, while
tmda-filter -M expects both recipient address and a sender address.

e.g,

$ tmda-inject -M bobby@peru.com
Traceback (most recent call last):
  File "./tmda-inject", line 107, in ?
    Util.filter_match(Defaults.FILTER_OUTGOING, recip)
  File "/home/jasonrm/cvs/tmda/dist/TMDA/Util.py", line 279, in filter_match
    filter.read(filename)
  File "/home/jasonrm/cvs/tmda/dist/TMDA/FilterParser.py", line 55, in read
    self.__parse(fp, filename)
  File "/home/jasonrm/cvs/tmda/dist/TMDA/FilterParser.py", line 96, in __parse
    raise e
TMDA.FilterParser.ParsingError: Filter contains parsing errors: /home/jasonrm/.tmda/filters/outgoing
        [line  3]: 'to_jason@mastaler.com bare'

(after fixing line 3)

$ tmda-inject -M bobby@peru.com
Checking /home/jasonrm/.tmda/filters/outgoing
---------------------------------------------
To: bobby@peru.com
---------------------------------------------
Sorry, no matching lines.

$ tmda-inject -M python-crypto@nic.surfnet.nl
Checking /home/jasonrm/.tmda/filters/outgoing
---------------------------------------------
To: python-crypto@nic.surfnet.nl
---------------------------------------------
MATCH: to python-crypto@nic.surfnet.nl ext=list-python-crypto

$ tmda-filter -M jason@mastaler.com bobby@peru.com
Checking /home/jasonrm/.tmda/filters/incoming
---------------------------------------------
To: jason@mastaler.com
From: bobby@peru.com
---------------------------------------------
Sorry, no matching lines.

$ tmda-filter -M jason@mastaler.com minhhoangnet@yahoo.com
Checking /home/jasonrm/.tmda/filters/incoming
---------------------------------------------
To: jason@mastaler.com
From: minhhoangnet@yahoo.com
---------------------------------------------
MATCH: from-file ~/.tmda/lists/blacklist drop

================================================================================

Also fixed a bug in to/from-dbm and body/headers-file which caused
sucessful matches to be ignored.